input:
  runs: "config/runs.csv"
  file_extension: ".pod5"
  file_regex: "[A-Z]{3}[0-9]{5}\\_[0-9a-z]{8}\\_[0-9a-z]{8}\\_[0-9]+"
  barcodes: "4-7"

dorado:
  path: "path/to/dorado"
  simplex:
    cuda: "auto"
    trim: "none"
    extra: ""
  demultiplexing: True

report:
  tools: ["pycoQC", "NanoPlot"]
